minikube image load "frontend-image:latest"
minikube image load "backend-image:latest"
minikube image load "postgres-image:latest"
minikube image load "authentication-image:latest"
minikube image load "portainer-image:latest"