/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LoginResponseDTO } from './LoginResponseDTO';
import {
    LoginResponseDTOFromJSON,
    LoginResponseDTOFromJSONTyped,
    LoginResponseDTOToJSON,
} from './LoginResponseDTO';

/**
 * 
 * @export
 * @interface LoginResponseDTORequestResponse
 */
export interface LoginResponseDTORequestResponse {
    /**
     * 
     * @type {LoginResponseDTO}
     * @memberof LoginResponseDTORequestResponse
     */
    response?: LoginResponseDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LoginResponseDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LoginResponseDTORequestResponse interface.
 */
export function instanceOfLoginResponseDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginResponseDTORequestResponseFromJSON(json: any): LoginResponseDTORequestResponse {
    return LoginResponseDTORequestResponseFromJSONTyped(json, false);
}

export function LoginResponseDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : LoginResponseDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LoginResponseDTORequestResponseToJSON(value?: LoginResponseDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': LoginResponseDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

