/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UserDTOPagedResponse
 */
export interface UserDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UserDTOPagedResponse
     */
    data?: Array<UserDTO> | null;
}

/**
 * Check if a given object implements the UserDTOPagedResponse interface.
 */
export function instanceOfUserDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDTOPagedResponseFromJSON(json: any): UserDTOPagedResponse {
    return UserDTOPagedResponseFromJSONTyped(json, false);
}

export function UserDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(UserDTOFromJSON)),
    };
}

export function UserDTOPagedResponseToJSON(value?: UserDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(UserDTOToJSON)),
    };
}

