/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { UserDTOPagedResponse } from './UserDTOPagedResponse';
import {
    UserDTOPagedResponseFromJSON,
    UserDTOPagedResponseFromJSONTyped,
    UserDTOPagedResponseToJSON,
} from './UserDTOPagedResponse';

/**
 * 
 * @export
 * @interface UserDTOPagedResponseRequestResponse
 */
export interface UserDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {UserDTOPagedResponse}
     * @memberof UserDTOPagedResponseRequestResponse
     */
    response?: UserDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the UserDTOPagedResponseRequestResponse interface.
 */
export function instanceOfUserDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDTOPagedResponseRequestResponseFromJSON(json: any): UserDTOPagedResponseRequestResponse {
    return UserDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function UserDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : UserDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserDTOPagedResponseRequestResponseToJSON(value?: UserDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': UserDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

